/**
 * Canvas Artifacts - Claude-style artifact generation for the canvas
 *
 * Artifacts are rich content nodes that can be generated by AI:
 * - Documents (markdown, rich text)
 * - Charts (bar, line, pie, etc.)
 * - Code blocks (with syntax highlighting)
 * - Images (AI generated or referenced)
 * - Tables (data grids)
 * - Diagrams (mermaid, flowcharts)
 */

// ============================================================================
// Artifact Types
// ============================================================================

export type ArtifactType =
  | 'document'      // Rich text / markdown document
  | 'code'          // Code block with syntax highlighting
  | 'chart'         // Data visualization
  | 'table'         // Data table/grid
  | 'diagram'       // Mermaid or flowchart
  | 'image'         // AI-generated or referenced image
  | 'embed'         // External embed (iframe)
  | 'prd'           // PRD document
  | 'ticket'        // BMAD ticket card
  | 'user-story';   // User story card

export interface BaseArtifact {
  id: string;
  type: ArtifactType;
  title: string;
  createdAt: number;
  updatedAt: number;
}

export interface DocumentArtifact extends BaseArtifact {
  type: 'document';
  content: string; // Markdown content
  format: 'markdown' | 'richtext' | 'plain';
}

export interface CodeArtifact extends BaseArtifact {
  type: 'code';
  content: string;
  language: string;
  filename?: string;
}

export interface ChartArtifact extends BaseArtifact {
  type: 'chart';
  chartType: 'bar' | 'line' | 'pie' | 'donut' | 'area' | 'scatter';
  data: {
    labels: string[];
    datasets: Array<{
      label: string;
      data: number[];
      color?: string;
    }>;
  };
}

export interface TableArtifact extends BaseArtifact {
  type: 'table';
  columns: Array<{ key: string; label: string; type?: 'string' | 'number' | 'date' }>;
  rows: Array<Record<string, unknown>>;
}

export interface DiagramArtifact extends BaseArtifact {
  type: 'diagram';
  diagramType: 'mermaid' | 'flowchart' | 'sequence' | 'class' | 'er';
  content: string; // Mermaid syntax or custom format
}

export interface ImageArtifact extends BaseArtifact {
  type: 'image';
  src: string;
  alt?: string;
  prompt?: string; // If AI-generated
  width?: number;
  height?: number;
}

export interface PRDArtifact extends BaseArtifact {
  type: 'prd';
  prdId?: string; // Reference to Convex PRD
  problem: string;
  solution: string;
  targetUser: string;
  features: string[];
  successCriteria: string[];
}

export interface TicketArtifact extends BaseArtifact {
  type: 'ticket';
  ticketId?: string; // Reference to Convex ticket
  asA: string;
  iWant: string;
  soThat: string;
  priority: 'P0' | 'P1' | 'P2' | 'P3';
  status: 'backlog' | 'todo' | 'in_progress' | 'review' | 'done';
  acceptanceCriteria?: string[];
}

export interface UserStoryArtifact extends BaseArtifact {
  type: 'user-story';
  asA: string;
  iWant: string;
  soThat: string;
  notes?: string;
}

export type Artifact =
  | DocumentArtifact
  | CodeArtifact
  | ChartArtifact
  | TableArtifact
  | DiagramArtifact
  | ImageArtifact
  | PRDArtifact
  | TicketArtifact
  | UserStoryArtifact;

// ============================================================================
// Context Reference Types (for @mentions)
// ============================================================================

export type ReferenceType =
  | 'ticket'        // @ticket:ARC-001
  | 'prd'           // @prd:product-name
  | 'project'       // @project:my-project
  | 'task'          // @task:task-id
  | 'note'          // @note:note-id
  | 'canvas'        // @canvas:canvas-id
  | 'memory'        // @memory:search-query
  | 'track'         // @track:song-name (jamz)
  | 'file'          // @file:path/to/file
  | 'skill'         // @skill:design-excellence
  | 'dimension'     // @dimension:kanban
  | 'tool';         // @tool:search_portfolio

export interface ContextReference {
  type: ReferenceType;
  id: string;
  displayName: string;
  preview?: string;
  data?: Record<string, unknown>;
}

// ============================================================================
// Artifact Detection from AI Responses
// ============================================================================

/**
 * Detect and extract artifacts from AI response content
 * Similar to how Claude detects artifacts in responses
 */
export function detectArtifacts(content: string): Array<{ artifact: Partial<Artifact>; raw: string }> {
  const artifacts: Array<{ artifact: Partial<Artifact>; raw: string }> = [];

  // Detect code blocks
  const codeBlockRegex = /```(\w+)?\n([\s\S]*?)```/g;
  let match;
  while ((match = codeBlockRegex.exec(content)) !== null) {
    const language = match[1] || 'text';
    const code = match[2].trim();

    // Check if it's a mermaid diagram
    if (language === 'mermaid') {
      artifacts.push({
        artifact: {
          type: 'diagram',
          diagramType: 'mermaid',
          title: 'Diagram',
          content: code,
        } as Partial<DiagramArtifact>,
        raw: match[0],
      });
    } else {
      artifacts.push({
        artifact: {
          type: 'code',
          title: `${language} code`,
          content: code,
          language,
        } as Partial<CodeArtifact>,
        raw: match[0],
      });
    }
  }

  // Detect JSON chart data
  const chartRegex = /```chart\n([\s\S]*?)```/g;
  while ((match = chartRegex.exec(content)) !== null) {
    try {
      const chartData = JSON.parse(match[1]);
      artifacts.push({
        artifact: {
          type: 'chart',
          title: chartData.title || 'Chart',
          chartType: chartData.type || 'bar',
          data: chartData.data,
        } as Partial<ChartArtifact>,
        raw: match[0],
      });
    } catch {
      // Invalid JSON, skip
    }
  }

  // Detect tables (markdown format)
  // Note: regex split to avoid Tailwind class extraction issue
  const tableSeparatorPattern = '[-' + ':' + '\\s|]+';
  const tableRegex = new RegExp('\\|(.+)\\|\\n\\|' + tableSeparatorPattern + '\\|\\n((?:\\|.+\\|\\n?)+)', 'g');
  while ((match = tableRegex.exec(content)) !== null) {
    const headerRow = match[1].split('|').map(s => s.trim()).filter(Boolean);
    const bodyRows = match[2].trim().split('\n').map(row =>
      row.split('|').map(s => s.trim()).filter(Boolean)
    );

    artifacts.push({
      artifact: {
        type: 'table',
        title: 'Table',
        columns: headerRow.map(h => ({ key: h.toLowerCase().replace(/\s+/g, '_'), label: h })),
        rows: bodyRows.map(row => {
          const obj: Record<string, string> = {};
          headerRow.forEach((h, i) => {
            obj[h.toLowerCase().replace(/\s+/g, '_')] = row[i] || '';
          });
          return obj;
        }),
      } as Partial<TableArtifact>,
      raw: match[0],
    });
  }

  // Detect user stories
  const userStoryRegex = /As a (.+?),?\s*I want (.+?),?\s*so that (.+?)(?:\.|$)/gi;
  while ((match = userStoryRegex.exec(content)) !== null) {
    artifacts.push({
      artifact: {
        type: 'user-story',
        title: 'User Story',
        asA: match[1].trim(),
        iWant: match[2].trim(),
        soThat: match[3].trim(),
      } as Partial<UserStoryArtifact>,
      raw: match[0],
    });
  }

  return artifacts;
}

// ============================================================================
// Create Artifact Node for Canvas
// ============================================================================

export function createArtifactNode(
  artifact: Partial<Artifact>,
  position: { x: number; y: number }
): {
  id: string;
  type: string;
  x: number;
  y: number;
  width: number;
  height: number;
  content: string;
  style?: Record<string, unknown>;
  artifact: Partial<Artifact>;
} {
  const baseNode = {
    id: `artifact-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    x: position.x,
    y: position.y,
    artifact,
  };

  // Size and style based on artifact type
  switch (artifact.type) {
    case 'document':
      return {
        ...baseNode,
        type: 'artifact-document',
        width: 400,
        height: 300,
        content: (artifact as DocumentArtifact).content || '',
        style: { fill: '#1e1e2e', border: '#6366f1' },
      };

    case 'code':
      return {
        ...baseNode,
        type: 'artifact-code',
        width: 450,
        height: 250,
        content: (artifact as CodeArtifact).content || '',
        style: { fill: '#0d1117', border: '#30363d' },
      };

    case 'chart':
      return {
        ...baseNode,
        type: 'artifact-chart',
        width: 400,
        height: 300,
        content: JSON.stringify((artifact as ChartArtifact).data || {}),
        style: { fill: '#1a1a2e', border: '#3b82f6' },
      };

    case 'table':
      return {
        ...baseNode,
        type: 'artifact-table',
        width: 500,
        height: 250,
        content: JSON.stringify({
          columns: (artifact as TableArtifact).columns,
          rows: (artifact as TableArtifact).rows,
        }),
        style: { fill: '#1a1a2e', border: '#10b981' },
      };

    case 'diagram':
      return {
        ...baseNode,
        type: 'artifact-diagram',
        width: 500,
        height: 400,
        content: (artifact as DiagramArtifact).content || '',
        style: { fill: '#1a1a2e', border: '#8b5cf6' },
      };

    case 'ticket':
    case 'user-story':
      return {
        ...baseNode,
        type: 'artifact-ticket',
        width: 320,
        height: 200,
        content: JSON.stringify(artifact),
        style: { fill: '#1a1a2e', border: '#f59e0b' },
      };

    case 'prd':
      return {
        ...baseNode,
        type: 'artifact-prd',
        width: 450,
        height: 350,
        content: JSON.stringify(artifact),
        style: { fill: '#1a1a2e', border: '#ec4899' },
      };

    case 'image':
      return {
        ...baseNode,
        type: 'artifact-image',
        width: (artifact as ImageArtifact).width || 400,
        height: (artifact as ImageArtifact).height || 300,
        content: (artifact as ImageArtifact).src || '',
        style: { fill: '#0a0a0a', border: '#525252' },
      };

    default:
      return {
        ...baseNode,
        type: 'artifact-generic',
        width: 300,
        height: 200,
        content: JSON.stringify(artifact),
        style: { fill: '#1a1a2e', border: '#6b7280' },
      };
  }
}

// ============================================================================
// Parse @references from text
// ============================================================================

export function parseReferences(text: string): Array<{ type: ReferenceType; query: string; raw: string }> {
  const references: Array<{ type: ReferenceType; query: string; raw: string }> = [];

  // Match @type:query or @type:"query with spaces"
  const refRegex = /@(ticket|prd|project|task|note|canvas|memory|track|file):(?:"([^"]+)"|(\S+))/gi;

  let match;
  while ((match = refRegex.exec(text)) !== null) {
    references.push({
      type: match[1].toLowerCase() as ReferenceType,
      query: match[2] || match[3],
      raw: match[0],
    });
  }

  return references;
}
